name: Sync to HuggingFace

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Install git-lfs
        run: |
          git lfs install
          git lfs track "*.pkl"
      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "farahhanif723@gmail.com"
          git config --global user.name "FarahHanif723"
          git remote add hf https://FarahHanif723:$HF_TOKEN@huggingface.co/spaces/Farah765/loaniq-credit-scoring
          git lfs push hf main --all
          git push hf main --force
